import{a as S,S as P,i as n}from"./assets/vendor-hwdYKDic.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&c(a)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function c(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const R="48935513-8997d7f633aa985d826258f4d",$="https://pixabay.com/api/",m=async(s,t)=>{try{return(await S.get($,{params:{key:R,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:40,page:t}})).data}catch(o){iziToast.error({message:"An error occurred while fetching images. Please try again later.",position:"topRight"}),console.error(o)}},h=document.querySelector(".gallery"),x=()=>{h.innerHTML=""},f=s=>{const t=s.map(({webformatURL:c,largeImageURL:e,tags:r,likes:a,views:v,comments:w,downloads:q})=>`<a class="gallery-item" href="${e}">
          <div class="photo-card">
            <img src="${c}" alt="${r}" />
            <div class="info">
              <p><b>Likes:</b> ${a}</p>
              <p><b>Views:</b> ${v}</p>
              <p><b>Comments:</b> ${w}</p>
              <p><b>Downloads:</b> ${q}</p>
            </div>
          </div>
        </a>`).join("");h.insertAdjacentHTML("beforeend",t),new P(".gallery a").refresh()},u=document.querySelector("#search-form"),O=document.querySelector(".form-input"),y=document.querySelector(".loader"),g=document.querySelector(".load-more");let i=1,l="",p=0;function b(){y.classList.add("active")}function d(){y.classList.remove("active")}function A(){g.style.display="block"}function L(){g.style.display="none"}u.addEventListener("submit",async s=>{if(s.preventDefault(),l=O.value.trim(),!l){n.warning({message:"Please enter a valid search query!",position:"topRight"});return}i=1,x(),b(),L();try{const t=await m(l,i),o=t.hits;if(d(),o.length===0){n.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),u.reset();return}f(o),u.reset(),p=t.totalHits,p>i*40&&A()}catch(t){d(),n.error({message:"An error occurred while fetching images. Please try again later.",position:"topRight"}),console.error(t)}});g.addEventListener("click",async()=>{i+=1,b();try{const t=(await m(l,i)).hits;d(),f(t);const{height:o}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"}),(t.length<40||i*40>=p)&&(L(),n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(s){d(),n.error({message:"An error occurred while loading more images.",position:"topRight"}),console.error(s)}});
//# sourceMappingURL=index.js.map
